spring:
    datasource:
        username: postgres
        password: 1234
        url: jdbc:postgresql://localhost:6969/benjamiches_db
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create

    banner:
        location: banner.txt
