spring:
    datasource:
        username: postgres
        password: 1234
        url: jdbc:postgresql://localhost:5432/benjamiche_db
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        hibernate:
            ddl-auto: create

    banner:
        location: banner.txt
